#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

volumes:
  model-cache:
  nextcloud:
  db:
  minio_data:
    driver: local

  
services:

  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'    
    volumes:
      - 'minio_data:/bitnami/minio/data'

    env_file:
      - .env 

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://${OBJECTSTORE_S3_HOST}:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/immichbucket;
      /usr/bin/mc policy set public myminio/immichbucket;
      exit 0;
      "  
    env_file:
      - .env 
    